# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce2dbf7c6cabdec069fe370cb9b1a9dadbe3a6daac9e821976c2519c2841940c6f0165c9c2103ad60a8d82cc4adb02b1b7684163829e0e14b79785e71a70b65b

test:
  secret_key_base: 1a418402aa98ceae1150e88725277003f20261f8baafac16f60694af01f1797907d7a48b83328f3a5f9f092ffac6be73adfe7785f1579f2ee9c9b9eeb63be02d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
